spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bd_tp_oo2
    username: root
    password: 'root'
    #url: ${DB_URL}
    #username: ${USERNAME}
    #password: ${PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect
  thymeleaf:
    cache: false